/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.radu.salesman.domain;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.*;
import javax.persistence.Entity;

// ----------- << imports@AAAAAAF4eqO50GjPkwU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4eqO50GjPkwU= >>
// ----------- >>

@Entity
@Table(name = "Carts")
public class Cart extends com.radu.salesman.domain.Entity<Long> {
    // ----------- << attribute.annotations@AAAAAAF4eseVrnKDrew= >>
    // ----------- >>
    private List<CartElement> cartElements;

    public Cart(List<CartElement> cartElements) {
        this.cartElements = cartElements;
    }

    public Cart() {
        this.cartElements = new ArrayList<>();
    }

    @Id
    @GeneratedValue(generator = "increment")
    @GenericGenerator(name = "increment", strategy = "increment")
    @Override
    public Long getId() {
        return super.getId();
    }

    @Override
    public void setId(Long id) {
        super.setId(id);
    }

    @OneToMany(mappedBy = "cart", targetEntity = CartElement.class, fetch = FetchType.EAGER)
    @LazyCollection(value = LazyCollectionOption.FALSE)
    public List<CartElement> getCartElements() {
        return cartElements;
    }

    public void setCartElements(List<CartElement> cartElements) {
        this.cartElements = cartElements;
    }

    public void addCartElement(CartElement cartElement) {
        this.cartElements.add(cartElement);
    }

    public void removeCartElement(CartElement cartElement) {
        this.cartElements.remove(cartElement);
    }

    public void clearCartElements() {
        this.cartElements.clear();
    }

    @Override
    public String toString() {
        return "CartRepository{" +
                ", cartElements=" + cartElements +
                '}';
    }
}
