/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.radu.salesman.domain;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.persistence.Entity;

// ----------- << imports@AAAAAAF4eqwVuWk3M94= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4eqwVuWk3M94= >>
// ----------- >>

@Entity
@Table(name = "Contacts")
public class Contact extends com.radu.salesman.domain.Entity<Long> {
    // ----------- << attribute.annotations@AAAAAAF4eq/U4mmng8Y= >>
    // ----------- >>
    private String firstname;

    // ----------- << attribute.annotations@AAAAAAF4erBx+WmwwmI= >>
    // ----------- >>
    private String lastname;

    // ----------- << attribute.annotations@AAAAAAF4erCYyWm44LA= >>
    // ----------- >>
    private String phoneNumber;

    // ----------- << attribute.annotations@AAAAAAF4fPOIXwyhk1g= >>
    // ----------- >>
    private String county;

    // ----------- << attribute.annotations@AAAAAAF4fPPP+Q4DhRo= >>
    // ----------- >>
    private String city;

    // ----------- << attribute.annotations@AAAAAAF4fPQMjA8oEGA= >>
    // ----------- >>
    private String address;

    public Contact(String firstname, String lastname, String phoneNumber, String county, String city, String address) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.phoneNumber = phoneNumber;
        this.county = county;
        this.city = city;
        this.address = address;
    }

    public Contact() {

    }

    @Id
    @GeneratedValue(generator="increment")
    @GenericGenerator(name="increment", strategy = "increment")
    @Override
    public Long getId() {
        return super.getId();
    }

    @Override
    public void setId(Long id) {
        super.setId(id);
    }

    @Column(name = "firstname")
    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Column(name = "lastname")
    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name = "phoneNumber")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "county")
    public String getCounty() {
        return county;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    @Column(name = "city")
    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "address")
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        return "Contact{" +
                ", firstname='" + firstname + '\'' +
                ", lastname='" + lastname + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", county='" + county + '\'' +
                ", city='" + city + '\'' +
                ", address='" + address + '\'' +
                '}';
    }
}
