/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.radu.salesman.domain;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.persistence.Entity;

// ----------- << imports@AAAAAAF4eqwyCWlhYtc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4eqwyCWlhYtc= >>
// ----------- >>

@Entity
@Table(name = "Payments")
public class Payment extends com.radu.salesman.domain.Entity<Long> {
    // ----------- << attribute.annotations@AAAAAAF4er4+BmyHD/o= >>
    // ----------- >>
    private String cardNumber;

    // ----------- << attribute.annotations@AAAAAAF4er57Y2y/unc= >>
    // ----------- >>
    private int expirationMonth;

    // ----------- << attribute.annotations@AAAAAAF4er7bu2z3Jm4= >>
    // ----------- >>
    private int expirationYear;

    // ----------- << attribute.annotations@AAAAAAF4er8QbW08kNg= >>
    // ----------- >>
    private String fullName;

    // ----------- << attribute.annotations@AAAAAAF4esInhW2Bao8= >>
    // ----------- >>
    private String cvv;

    public Payment(String cardNumber, int expirationMonth, int expirationYear, String fullName, String cvv) {
        this.cardNumber = cardNumber;
        this.expirationMonth = expirationMonth;
        this.expirationYear = expirationYear;
        this.fullName = fullName;
        this.cvv = cvv;
    }

    public Payment() {

    }

    @Id
    @GeneratedValue(generator="increment")
    @GenericGenerator(name="increment", strategy = "increment")
    @Override
    public Long getId() {
        return super.getId();
    }

    @Override
    public void setId(Long id) {
        super.setId(id);
    }

    @Column(name = "cardNumber")
    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    @Column(name = "expirationMonth")
    public int getExpirationMonth() {
        return expirationMonth;
    }

    public void setExpirationMonth(int expirationMonth) {
        this.expirationMonth = expirationMonth;
    }

    @Column(name = "expirationYear")
    public int getExpirationYear() {
        return expirationYear;
    }

    public void setExpirationYear(int expirationYear) {
        this.expirationYear = expirationYear;
    }

    @Column(name = "fullName")
    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @Column(name = "cvv")
    public String getCvv() {
        return cvv;
    }

    public void setCvv(String cvv) {
        this.cvv = cvv;
    }

    @Override
    public String toString() {
        return "Payment{" +
                ", cardNumber='" + cardNumber + '\'' +
                ", expirationMonth=" + expirationMonth +
                ", expirationYear=" + expirationYear +
                ", fullName='" + fullName + '\'' +
                ", cvv='" + cvv + '\'' +
                '}';
    }
}
