/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.radu.salesman.domain;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.persistence.Entity;

// ----------- << imports@AAAAAAF4epzW5GfWeRk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4epzW5GfWeRk= >>
// ----------- >>

@Entity
@Table(name = "Products")
public class Product extends com.radu.salesman.domain.Entity<Long> {
    // ----------- << attribute.annotations@AAAAAAF4erqv4GvSoj4= >>
    // ----------- >>
    private String name;

    // ----------- << attribute.annotations@AAAAAAF4err6zmwKozg= >>
    // ----------- >>
    private int quantity;

    // ----------- << attribute.annotations@AAAAAAF4ertA8GxPsBA= >>
    // ----------- >>
    private float price;

    public Product(long id, String name, int quantity, float price) {
        setId(id);
        this.name = name;
        this.quantity = quantity;
        this.price = price;
    }

    public Product(String name, int quantity, float price) {
        this.name = name;
        this.quantity = quantity;
        this.price = price;
    }

    public Product() {

    }

    @Id
    @GeneratedValue(generator="increment")
    @GenericGenerator(name="increment", strategy = "increment")
    @Override
    public Long getId() {
        return super.getId();
    }

    @Override
    public void setId(Long id) {
        super.setId(id);
    }

    @Column(name = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "quantity")
    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Column(name = "price")
    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    @Override
    public String toString() {
        return name;
    }
}
