/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.radu.salesman.domain;

// ----------- << imports@AAAAAAF4eqJdu2h5SqM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4eqJdu2h5SqM= >>
// ----------- >>
public enum Role {
    USER, ADMIN

    // ----------- << enum.extras@AAAAAAF4eqJdu2h5SqM= >>
    // ----------- >>
}
