/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.radu.salesman.domain;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.persistence.Entity;

// ----------- << imports@AAAAAAF4eqGTwmgl7JQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4eqGTwmgl7JQ= >>
// ----------- >>

@Entity
@Table(name = "Users")
public class User extends com.radu.salesman.domain.Entity<Long> {
    // ----------- << attribute.annotations@AAAAAAF4eqfDHGkIY/k= >>
    // ----------- >>
    private String username;

    // ----------- << attribute.annotations@AAAAAAF4eqiKJGkQLbw= >>
    // ----------- >>
    private String password;

    // ----------- << attribute.annotations@AAAAAAF4erdyj2sAr/8= >>
    // ----------- >>
    private Role role;

    // ----------- << attribute.annotations@AAAAAAF4eqkw52kgwfQ= >>
    // ----------- >>
    private Contact contact;

    // ----------- << attribute.annotations@AAAAAAF4eqqDOGkutSs= >>
    // ----------- >>
    private Payment payment;

    // ----------- << attribute.annotations@AAAAAAF4eqzW9mmOtA0= >>
    // ----------- >>
    private Cart cart;

    public User(String username, String password, Role role, Contact contact, Payment payment, Cart cart) {
        this.username = username;
        this.password = password;
        this.role = role;
        this.contact = contact;
        this.payment = payment;
        this.cart = cart;
    }

    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public User() {

    }

    @Id
    @GeneratedValue(generator="increment")
    @GenericGenerator(name="increment", strategy = "increment")
    @Override
    public Long getId() {
        return super.getId();
    }

    @Override
    public void setId(Long id) {
        super.setId(id);
    }

    @Column(name = "username")
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password")
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Enumerated(EnumType.STRING)
    @Column(name = "role", columnDefinition = "enum('USER','ADMIN')")
    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    @OneToOne
    @JoinColumn(name = "contactId", referencedColumnName = "id")
    public Contact getContact() {
        return contact;
    }

    public void setContact(Contact contact) {
        this.contact = contact;
    }

    @OneToOne
    @JoinColumn(name = "paymentId", referencedColumnName = "id")
    public Payment getPayment() {
        return payment;
    }

    public void setPayment(Payment payment) {
        this.payment = payment;
    }

    @OneToOne
    @JoinColumn(name = "cartId", referencedColumnName = "id")
    public Cart getCart() {
        return cart;
    }

    public void setCart(Cart cart) {
        this.cart = cart;
    }

    @Override
    public String toString() {
        return "User{" +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", role=" + role +
                ", contact=" + contact +
                ", payment=" + payment +
                ", cart=" + cart +
                '}';
    }
}
