/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.radu.salesman.ui.gui;

// ----------- << imports@AAAAAAF5DxvQTX9uBR0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5DxvQTX9uBR0= >>
// ----------- >>
public enum AppLayout {
    AUTH, MAIN, MNG_PRD, CART, INS_DATA

    // ----------- << enum.extras@AAAAAAF5DxvQTX9uBR0= >>
    // ----------- >>
}
