/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.radu.salesman.ui.gui;

import com.radu.salesman.controllers.Controller;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.ButtonType;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import com.radu.salesman.service.Service;
import com.radu.salesman.ui.UI;

import java.util.EnumMap;

// ----------- << imports@AAAAAAF4xnopqNYNoss= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF4xnopqNYNoss= >>
// ----------- >>

public class MainGUI extends Application implements UI {
    private static EnumMap<AppLayout, Pane> appLayoutMap;
    private static Scene appScene;

    private static Pane loadFXML(String location) throws Exception {
        FXMLLoader fxmlLoader = new FXMLLoader();
        fxmlLoader.setLocation(MainGUI.class.getResource(location));
        return fxmlLoader.load();
    }

    // ----------- << method.annotations@AAAAAAF5Dxp4RnmgQ78= >>
    // ----------- >>
    public static void activatePane(AppLayout appLayout) {
        // ----------- << method.body@AAAAAAF5Dxp4RnmgQ78= >>
        // ----------- >>
        MainGUI.appScene.setRoot(appLayoutMap.get(appLayout));
    }

    public static void showAlert(Alert.AlertType type, String content, ButtonType... buttons) {
        Alert alert = new Alert(type, content, buttons);
        alert.setResizable(true);
        alert.show();
    }

    public void setService(Service service) {
        Controller.setService(service);
    }

    @Override
    public void init() {
        appScene = new Scene(new Pane());
        appLayoutMap = new EnumMap<>(AppLayout.class);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        appLayoutMap.put(AppLayout.AUTH, loadFXML("/fxml/authLayout.fxml"));
        appLayoutMap.put(AppLayout.MAIN, loadFXML("/fxml/mainLayout.fxml"));
        appLayoutMap.put(AppLayout.CART, loadFXML("/fxml/cartLayout.fxml"));
        appLayoutMap.put(AppLayout.MNG_PRD, loadFXML("/fxml/manageProductsLayout.fxml"));
        appLayoutMap.put(AppLayout.INS_DATA, loadFXML("/fxml/deliveryDetailsLayout.fxml"));

        activatePane(AppLayout.AUTH);

        primaryStage.setScene(appScene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }

    // ----------- << method.annotations@AAAAAAF4xnrp/dderGs= >>
    // ----------- >>
    @Override
    public void run() {
        // ----------- << method.body@AAAAAAF4xnrp/dderGs= >>
        // ----------- >>
        main(null);
    }
    // ----------- << class.extras@AAAAAAF4xnopqNYNoss= >>
    // ----------- >>
}
