/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.radu.salesman.controllers;

import com.radu.salesman.domain.User;
import com.radu.salesman.service.Service;

// ----------- << imports@AAAAAAF5Dw+uKzpwNAg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5Dw+uKzpwNAg= >>
// ----------- >>
public class Controller {
    // ----------- << attribute.annotations@AAAAAAF5DxSpFVbH5zI= >>
    // ----------- >>
    static protected Service service = null;

    // ----------- << attribute.annotations@AAAAAAF5DxOkqk+sFHY= >>
    // ----------- >>
    static protected User currentUser = null;

    static protected float totalPrice = 0.0f;

    // ----------- << method.annotations@AAAAAAF5Dx/sTJ2hCbg= >>
    // ----------- >>
    public static void setService(Service service) {
        // ----------- << method.body@AAAAAAF5Dx/sTJ2hCbg= >>
        // ----------- >>
        Controller.service = service;
    }

    // ----------- << method.annotations@AAAAAAF5Dx8KoJdV0A4= >>
    // ----------- >>
    public static void setCurrentUser(User currentUser) {
        // ----------- << method.body@AAAAAAF5Dx8KoJdV0A4= >>
        // ----------- >>
        Controller.currentUser = currentUser;
    }

    public static void setTotalPrice(float totalPrice) {
        Controller.totalPrice = totalPrice;
    }
    // ----------- << class.extras@AAAAAAF5Dw+uKzpwNAg= >>
    // ----------- >>
}
